kind: pipeline
type: exec
name: deploy to client

clone:
  disable: true

platform:
  os: windows
  arch: amd64

steps:
- name: clone
  commands:
  - git clone ssh://git@gogs.local:10022/kamikadzem22/cgminer_exporter.git .
  - git checkout $DRONE_COMMIT

- name: stop  old service
  failure: ignore
  commands:
  - nssm stop cgminer_exporter

- name: remove old service
  failure: ignore
  commands:
  - nssm remove cgminer_exporter confirm

- name: remove old files
  failure: ignore
  commands:
  - Remove-Item -Recurse -Force -Path C:\\Monitoring\\cgminer_exporter

- name: copy files
  commands:
  - mkdir C:\\Monitoring\\cgminer_exporter
  - xcopy * C:\\Monitoring\\cgminer_exporter /exclude:.drone.yml

- name: create service
  commands:
  - nssm install cgminer_exporter uvicorn.exe main:app --workers 4 --port 9154
  - nssm set cgminer_exporter AppDirectory C:\\Monitoring\\cgminer_exporter
- name: start service
  commands:
  - nssm restart cgminer_exporter

trigger:
  branch:
  - master

node:
  target: monitoring