kind: pipeline
type: exec
name: deploy to client

clone:
  disable: true

platform:
  os: windows
  arch: amd64

steps:
- name: clone
  commands:
  - git clone ssh://git@gogs.local:10022/kamikadzem22/cgminer_exporter.git .
  - git checkout $DRONE_COMMIT

node:
  target: monitoring